# Generated by Django 5.1.2 on 2024-10-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=250)),
                ("imagen", models.ImageField(upload_to="images/")),
                ("preco", models.FloatField()),
                ("unidade", models.CharField(default="UND", max_length=3)),
            ],
        ),
    ]
