# Generated by Django 5.1.2 on 2024-10-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="content_type",
            field=models.CharField(default="", max_length=20),
        ),
    ]
