# Generated by Django 5.1.2 on 2024-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0002_produtos_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="descricao",
            field=models.CharField(max_length=2000),
        ),
    ]
