# Generated by Django 5.1.2 on 2024-10-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0003_alter_produtos_descricao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Imagens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_imagen", models.CharField(max_length=200)),
                ("content_type", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="produtos",
            name="content_type",
        ),
    ]
