# Generated by Django 5.1.2 on 2024-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_imagens_remove_produtos_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagens",
            name="imagen",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
