# Generated by Django 5.1.2 on 2024-10-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0007_alter_iamgem_code_alter_iamgem_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Iamgem",
            new_name="Imagem",
        ),
        migrations.RenameField(
            model_name="produtos",
            old_name="iamgem",
            new_name="imagem",
        ),
    ]
