# Generated by Django 5.1.2 on 2024-10-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0011_alter_itemspedido_item_alter_itemspedido_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemspedido",
            name="preco",
            field=models.FloatField(default=1),
        ),
    ]
