# Generated by Django 5.1.2 on 2024-10-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0013_remove_itemspedido_item_itemspedido_produto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemspedido",
            name="pedido",
        ),
        migrations.RemoveField(
            model_name="itemspedido",
            name="produto",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="ItemsPedido",
        ),
    ]
