# Generated by Django 5.1.2 on 2024-10-17 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0015_pedidovenda"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItensPedidoVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pedido_venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pedido_venda",
                        to="vendas.pedidovenda",
                    ),
                ),
            ],
        ),
    ]
