# Generated by Django 5.1.2 on 2024-10-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0018_itenspedidovenda_item_venda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itenspedidovenda",
            name="item_venda",
            field=models.CharField(default="0000", max_length=4),
        ),
    ]
