# Generated by Django 5.1.2 on 2024-10-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0019_alter_itenspedidovenda_item_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="itenspedidovenda",
            name="qtd_venda",
            field=models.FloatField(default=1),
        ),
    ]
