# Generated by Django 5.1.2 on 2024-10-18 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0023_alter_pedidovenda_cliente_venda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidovenda",
            name="cliente_venda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
