# Generated by Django 5.1.2 on 2024-10-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0024_alter_pedidovenda_cliente_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="estoque",
            field=models.FloatField(default=0),
        ),
    ]
